### ISSUE TITLE
Compiled Archon binary cannot load Bedrock via Pi provider

### ISSUE THREAD

**Issue by pondycrane** [coleam00/Archon#2154]
## Summary

- What broke: Archon compiled Bun binary fails when a Pi workflow node uses `amazon-bedrock/*` — `ResolveMessage: Cannot find module './bedrock-converse-stream.js' from '/$bunfs/root/archon…'`. Same model works with standalone `pi` CLI; `cursor/*` via pi-cursor works in the same Archon binary.
- When it started (if known): Observed on Archon CLI v0.5.0 (`Build: binary`, linux-x64). Not tied to a recent local config change; fails as soon as a Pi node targets Bedrock.
- Severity: `major`

## Steps to Reproduce

1. Install the compiled Archon binary (`curl -fsSL https://archon.diy/install | bash` or equivalent). Confirm `archon version` reports `Build: binary`.
2. Configure AWS Bedrock auth (e.g. `AWS_PROFILE=<profile>`, `AWS_REGION=us-east-1`, `aws sso login --profile <profile>`). Ensure standalone Pi works:

   ```bash
   AWS_PROFILE=<profile> AWS_REGION=us-east-1 \
     pi --provider amazon-bedrock \
        --model us.anthropic.claude-haiku-4-5-20251001-v1:0 \
        -p --no-session --mode text \
        "Reply with exactly: bedrock-ok"
   ```

3. Run a minimal Pi workflow (any catalog `amazon-bedrock/*` id):

   ```yaml
   name: repro-bedrock-pi
   nodes:
     - id: via_bedrock
       provider: pi
       model: amazon-bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0
       allowed_tools: []
       prompt: |
         Reply with exactly: bedrock-ok
   ```

   ```bash
   archon workflow run repro-bedrock-pi
   ```

## Expected vs Actual

- **Expected**: Pi provider invokes Bedrock and returns a response (same as standalone `pi`).
- **Actual**: Node fails with Bun module resolution error for `./bedrock-converse-stream.js` under `/$bunfs/root/archon…`.

## User Flow

```
  User                         Archon (compiled binary)              Pi SDK (in-process)
  ────                         ────────────────────────              ───────────────────
  workflow run ──────────────▶ loads provider: pi
                               resolves model amazon-bedrock/…
                               starts node via_bedrock ─────────────▶ ModelRegistry finds model
                                                                     tries lazy Bedrock load
                               [X] ResolveMessage ◀────────────────── import './bedrock-converse-stream.js'
                                   (module missing in /$bunfs/…)
  sees DAG node failure ◀───── surfaces SDK error
```

Contrast (works):

```
  User                         pi CLI (standalone)                   Bedrock
  ────                         ───────────────────                   ───────
  pi --provider amazon-bedrock ▶ Bun entry calls
                                  setBedrockProviderModule(…)
                                 streams prompt ───────────────────▶ response
  sees bedrock-ok ◀──────────── returns text
```

## Environment

- Platform: CLI
- Database: SQLite
- Running in worktree? `Yes` (default Archon DAG worktree; also fails conceptually at provider load before tools matter)
- OS: Linux x64 (Coder workspace)
- Archon: v0.5.0, `Build: binary`, Git commit `92b9bba` (local install)
- Related local stack (not required to repro): Pi + `npm:@schultzp2020/pi-cursor` for Cursor models

## Logs

```
DAG workflow '…' completed with failures:
  'via_bedrock': Node 'via_bedrock' failed: SDK returned error —
  ResolveMessage: Cannot find module './bedrock-converse-stream.js'
  from '/$bunfs/root/archon.new'
```

(Redacted: no tokens in this error path.)

## Impact

- Affected workflows/commands: Any workflow / chat using `provider: pi` with `model: amazon-bedrock/…` (or tiers mapped to Bedrock). Cursor/`cursor/*` and other non-Bedrock Pi models unaffected.
- Reproduction rate: Always
- Workaround available? Yes — shell out to standalone `pi` CLI from a workflow `bash:` node for Bedrock nodes; keep Cursor on `provider: pi`. Not in-process Archon Pi Bedrock.
- Data loss risk? `No`

## Scope

- Package(s) likely involved: `cli|providers` (community Pi provider embed in compiled binary)
- Module (if known): Pi community provider load path inside Bun compile; missing Bedrock Bun registration analogous to Pi’s `setBedrockProviderModule` / `bun/register-bedrock`

## Related

- Pi issue (same failure class for Pi’s own binary): https://github.com/earendil-works/pi/issues/2349
- Pi fix: https://github.com/earendil-works/pi/pull/2350 (`setBedrockProviderModule` in Bun entrypoint)
- Suggested direction: Archon’s compiled entry should register Bedrock the same way before any `amazon-bedrock/*` use, and add a compiled-binary smoke test for Bedrock.

**Comment by Wirasm** [comment]
Fixed in #2174 (merged to dev). Root cause confirmed: Bun's `--compile` can't follow Pi's computed-specifier indirection for the Bedrock backend, so `@aws-sdk/client-bedrock-runtime` was never embedded in the binary. The fix mirrors Pi's own binary shim (earendil-works/pi#2350) — `PiProvider` now registers the Bedrock module override once per process via `setBedrockProviderModule()`, fed through the static `pi-ai/compat` + `/bedrock-provider` subpaths Bun does bundle.

Verified on a compiled binary: the pre-fix `Cannot find module './bedrock-converse-stream.js'` becomes a normal AWS auth error (module now loads), with no impact on other Pi backends or dev mode. A compiled-binary provider-load smoke to guard this class of regression is tracked in #2170. Thanks for the excellent write-up — your diagnosis was exactly right.
