### PR TITLE
fix(workflows): enforce hermetic include references

### LINKED ISSUE #2450: fix(workflows): enforce hermetic composed-workflow boundaries across every reference surface
> **Body rewritten 2026-08-13.** Named `inputs:` / caller `with:` now provide the intended boundary. This issue is narrowed to making that boundary hermetic across every live reference surface.

## Problem

A composed workflow file must have an explicit interface. Every value crossing from the caller must arrive through a declared input supplied by `with:`. A composed workflow must not bind directly to a caller node merely because both files happen to contain a compatible node ID.

Current coverage is incomplete because reference parsing/rewriting is spread across multiple grammars and surfaces:

- canonical `$id.output[.field]` references;
- `when:` shorthand `$id.field`;
- inline versus command-backed bodies;
- recursively nested `loop_group` bodies;
- approval rejection prompts and other less-common live fields.

An omitted surface can accidentally bind to a caller node after composition. That makes the reusable block depend on hidden parent context that cannot be seen from its signature.

Command files are the preferred home for substantial prompts, so command-backed validation is core behavior rather than a best-effort edge case. Named script files are programs rather than prompt templates: they receive caller data only through declared input environment variables and must not gain implicit caller-node template access.

## Desired model

Each workflow file owns a lexical node namespace.

Inside a composed workflow:

- references to nodes owned by that workflow are internal and are rebound to deterministic composed IDs;
- references outside that workflow boundary are rejected;
- caller data enters only through declared `$INPUTS.<name>` values;
- `with:` may obtain those values from caller outputs, but the callee receives a bound value—not live access to the caller namespace;
- a reference never becomes valid merely because the parent happens to contain a node with the same ID.

Valid:

```yaml
# parent
- id: gather
  prompt: Gather context
- id: review
  include: review-block
  with:
    context: $gather.output
```

```yaml
# review-block
inputs:
  context: { required: true }
nodes:
  - id: judge
    prompt: Review $INPUTS.context
```

Invalid inside `review-block`, even if the parent has `gather`:

```yaml
- id: judge
  prompt: Review $gather.output
```

## Scope

- Define and enforce the workflow-file namespace boundary.
- Enumerate every live node-output reference and substitution surface, recursively.
- Parse canonical output references and `when:` shorthand consistently.
- Rewrite workflow-local references to composed IDs.
- Reject undeclared external/caller references before execution.
- Resolve and validate command-backed bodies using execution-equivalent precedence where possible.
- Cover approval rejection prompts, nested bodies, workflow caller fields, and future substitution surfaces.
- Treat resolved command prompt files as live prompt/reference surfaces with the same hermetic rules as inline prompts.
- Treat named script files as opaque programs: pass declared inputs through the documented environment contract, but do not introduce `$caller.output` source rewriting inside arbitrary program files.
- Preserve documented workflow-local enclosing-scope rules for nested nodes.
- Produce source-oriented errors naming the workflow, node/nested path, field or command, offending reference, and `inputs:`/`with:` migration.
- Revalidate the fully composed graph for dangling references, duplicate IDs, and cycles.

Concrete surfaces include at least:

- `prompt`, `bash`, `script`, `cancel`, and `when`;
- loop prompt/condition/command bodies;
- all recursively nested `loop_group` nodes and conditions;
- top-level and nested command-backed bodies;
- approval messages and rejection prompts where substitution is live;
- workflow input/`with:`/fan-out item references;
- system/agent prompt fields wherever node-output substitution is supported.

Validation and rewriting must share the runtime's definition of whether a reference in Markdown/code text is live. A documentation example must not be rejected if runtime substitution deliberately ignores it; a live fenced occurrence must not be ignored if runtime substitution consumes it.

## Command-backed content

A command file is not a loophole in the boundary.

- If its body is resolvable during validation, validate it.
- If a composed command body cannot be resolved at that stage, do not silently claim the workflow is hermetic.
- Surface a clear validation limitation/error naming the command and lookup scopes, or provide an equivalent guaranteed check before execution.
- Never proceed by silently allowing an unvalidated external reference.

The exact phase may differ between `include:` and future parent-run composition, but the observable boundary must be the same.

Named script files follow a different, explicit rule: their source is not a workflow template. The engine supplies declared `INPUTS_<UPPER_SNAKE>` environment values and captures stdout; it does not scan or rewrite arbitrary `$node.output`-looking text inside TypeScript, JavaScript, Python, or shell programs.

## Non-scope

- Another parent-context declaration syntax.
- Structured value schemas (#2453).
- The parent-run executor rewrite (#1764).
- Runtime-width fan-out (#2512).
- Changes to `when:` operators/precedence.
- Worktree/container isolation or artifact policy.
- A separately governed launch primitive.

This issue is a correctness slice and does not gate #1764. #1764 must preserve declared inputs and must not intentionally add caller-scope lookup; this issue supplies exhaustive coverage and errors independently.

## Compatibility

- Hermetic workflows are unchanged.
- Internal workflow-local references continue to work after namespacing.
- Caller values already passed through `inputs:`/`with:` are unchanged.
- Explicitly supported workflow-local enclosing references in nested bodies remain valid.
- Workflows relying on accidental caller-ID binding become validation errors with migration guidance.
- No database migration is required.

## Acceptance

- [ ] A composed `$caller.output` reference is rejected whether or not the parent has a matching node.
- [ ] `when: $caller.field == ...` is recognized and rejected across the boundary.
- [ ] Internal canonical and shorthand references are namespaced and keep working.
- [ ] Passing `$caller.output` through `with:` and reading `$INPUTS.<name>` is valid.
- [ ] Inline top-level and recursively nested nodes are covered.
- [ ] Top-level, loop, and nested command-backed bodies are covered.
- [ ] Package-local command files can consume declared inputs while direct caller-node references remain rejected.
- [ ] Named script files receive only declared input environment values and do not gain implicit caller-node substitution.
- [ ] Approval rejection prompts and every other live runtime substitution surface are covered.
- [ ] Workflow input/`with:`/fan-out item reference fields are covered.
- [ ] Unresolved command content cannot silently bypass the hermetic guarantee.
- [ ] Errors name the source workflow, source node/nested path, surface, offending reference, and migration.
- [ ] Runtime and validation agree on documentation-only versus live references.
- [ ] Post-composition validation catches dangling refs, duplicate IDs, and cycles.
- [ ] Tests cover both current `include:` and #1764's parent-run composition path.
- [ ] Tests cover a parent with a colliding node ID and a parent without one.
- [ ] Existing valid workflow-local nested-scope references remain valid.

## Related and issue consolidation

- #2475 and #2477 are concrete blind spots and should remain independently actionable while cross-linked here.
- #2488's exhaustive walker is one implementation path, not a prerequisite.
- #2453 owns structured declared values.
- #1764 owns parent-run composition identity/lifecycle.
- #2512 owns runtime-width instances.

## Related

#2453 · #1764 · #2512 · #2475 · #2477 · #2488 · #2214 · #2449

### PR DESCRIPTION
**Pull request by Wirasm**
## Summary

- Problem: included workflows could bind undeclared parent state through shorthand `when:`, rejection prompts, Markdown refs, or deferred command bodies.
- Why it matters: reusable workflows need a hermetic declared interface; caller-ID collisions could consume the wrong governed data.
- What changed: validation covers every live current reference surface, and included named commands are resolved, validated, snapshotted, namespaced, and input-bound at load time.
- What did **not** change: no parent-run execution, structured I/O, runtime fan-out, provider capability, database, expression-language, or named-script templating changes.

### Before

```
include command-first block -> flatten child, defer command body
matching parent id          -> hidden child ref can bind at runtime
```

### After

```
include command-first block -> [resolve + snapshot command body]
declared caller `with:`     -> [bind `$INPUTS`]
child-local refs            -> [validate + namespace]
hidden ref/unreadable body  -> [actionable load error]
executor                    -> deterministic flat DAG
```

### Before

```
workflow-discovery -> include-expander -> flat DAG -> dag-executor
       |                   |                             |
       +- reads commands   +- best-effort scan           +- loads command again
loader -> partial live-surface validation
```

### After

```
workflow-discovery -> [~] include-expander ==> flat DAG -> dag-executor
       |                     |
       +- reads commands ----+- validate + materialize + bind + namespace
[~] loader -> validates canonical refs, when shorthand, and rejection prompts
```

**Connection inventory**:

| From | To | Status | Notes |
|------|----|--------|-------|
| workflow discovery | include expander | **modified** | Resolved include command bodies are compilation inputs |
| loader | include expander | **modified** | Shared validation proves the child namespace before flattening |
| include expander | DAG executor | **modified** | Included commands arrive as deterministic prompt nodes |
| runtime substitution | validation/rewrite walkers | **modified** | Markdown and rejection surfaces now agree |
| workflow engine | docs/defaults | **modified** | Documents compilation and non-live example placeholders |

## Label Snapshot

- Risk: `risk: medium`
- Size: `size: L`
- Scope: `workflows`, `docs`, `tests`
- Module: `workflows:composition`

## Change Metadata

- Change type: `bug`
- Primary scope: `workflows`

## Linked Issue

- Closes #2450
- Related #1764, #2453, #2512, #2475, #2477, #2488
- Depends on #2532 (merged)
- Supersedes # N/A

## Validation Evidence (required)

```bash
bun test packages/workflows/src/include-expander.test.ts packages/workflows/src/workflow-discovery-command-scan.test.ts  # 69 pass
bun test packages/workflows/src/loader.test.ts  # 249 pass
bun --filter @archon/workflows test  # pass
bun x tsc --noEmit -p packages/workflows/tsconfig.json  # pass
bun x eslint <changed workflow source files> --max-warnings 0  # pass
bun run format:check  # pass
bun run check:bundled  # pass
bun run test:install  # pass
bun run validate  # exits 2 at pre-existing check:pi-vendor-map drift
bun run test  # unrelated existing CLI/server failures under parallel full-suite run
```

- Evidence provided: collision/no-collision, recursive commands, declared inputs, rejection prompts, shorthand, Markdown-live, unresolved-command, package-command, and composed graph tests.
- No command was intentionally skipped. `bun run validate` before and after implementation stops at identical installed Pi SDK/vendor-map drift. Independent broad gates show the same dependency drift in docs/providers; full parallel tests report unrelated CLI/server mock-sensitive failures. The workflows package and changed-file gates pass. CI is authoritative.

This preserves load-time composition and the flat static DAG; it adds no computation or expression surface. See `packages/docs-web/src/content/docs/reference/workflow-language-constitution.md`.

## Security Impact (required)

- New permissions/capabilities? (`No`)
- New external network calls? (`No`)
- Secrets/tokens handling changed? (`No`)
- File system access scope changed? (`No`)
- If any `Yes`, describe risk and mitigation: N/A. Existing discovery reads the same paths; included command content is now snapshotted into the compiled definition.

## Compatibility / Migration

- Backward compatible? (`No` — intentionally rejects hidden caller bindings and unresolved included commands)
- Config/env changes? (`No`)
- Database migration needed? (`No`)
- Upgrade: migrate hidden references to child `inputs:` plus caller `with:`. Ensure included commands resolve in package/project/user/enabled bundled scopes. Named scripts remain opaque and use `INPUTS_*` env values.

## Human Verification (required)

- Verified scenarios: parent collision and no collision; local/enclosing nested refs; command and loop-command inputs; package/configured lookup; rejection prompts; shorthand `when:`; fenced refs; unresolved commands.
- Edge cases checked: rewrite-before-input ordering keeps passed parent refs parent-scoped; nested IDs remain body-local; named scripts remain untouched.
- What was not verified: #1764 parent-run composition, which does not exist yet and must add parity tests when implemented.

## Side Effects / Blast Radius (required)

- Affected subsystems/workflows: workflow loading/discovery, include expansion, bundled workflow examples, include docs.
- Potential unintended effects: included command nodes appear as compiled prompt nodes; canonical refs used as Markdown examples must become placeholders.
- Guardrails/monitoring: source-oriented load errors, focused discovery tests, workflows package suite, post-expansion validation.

## Rollback Plan (required)

- Fast rollback: revert this PR.
- Feature flags/config toggles: none.
- Observable symptoms: validation errors name the include, workflow, node path, command/field, offending ref, and `inputs:`/`with:` migration.

## Risks and Mitigations

- Risk: snapshotting changes when command edits become visible.
  - Mitigation: rediscovery/reload recompiles current content, preserving deterministic composition.
- Risk: stricter Markdown handling invalidates examples.
  - Mitigation: runtime already substituted them; bundled examples now use `$<node-id>.output`, and docs explain the rule.
- Risk: a new substitution surface could drift.
  - Mitigation: synchronized walker comments and parity tests enumerate the four passes.

## Summary by CodeRabbit

* **New Features**
  * Included workflows and loop commands now expand into prompts with inputs and properly scoped references.
  * Output references work across prompts, conditions, approval messages, code spans, and loop commands.
  * Included commands support custom folders and nested workflow structures.

* **Bug Fixes**
  * Invalid, unresolved, or out-of-scope references now fail loading with clearer errors.
  * Prevented incorrect resolution against similarly named parent nodes.
  * Resumed loops retain their paused prompt, including composed commands.

* **Documentation**
  * Standardized workflow output-reference examples and syntax.

### CODE REVIEW

**Comment by Wirasm** [comment]
## PR Review Summary

### Critical Issues (0 found)
| Agent | Issue | Location |
|-------|-------|----------|
| — | — | — |

### Important Issues (0 found)
| Agent | Issue | Location |
|-------|-------|----------|
| — | — | — |

### Suggestions (3 found)
| Agent | Suggestion | Location |
|-------|------------|----------|
| code-simplifier | Consider sharing the output-ref and input-macro node-text traversal after the behavior stabilizes. Deferred here because the two walkers intentionally cover different surfaces and a refactor would enlarge a correctness fix. | `packages/workflows/src/include-expander.ts:149` |
| code-simplifier | Consider extracting the repeated known-reference predicate and using `matchAll` in DAG validation. Deferred as non-blocking polish. | `packages/workflows/src/loader.ts:421` |
| code-simplifier | Normalize the optional command map once outside the include loop. Deferred as negligible and unrelated to correctness. | `packages/workflows/src/include-expander.ts:600` |

### Strengths
- Hermetic validation now covers canonical refs, `when:` shorthand, approval rejection prompts, Markdown-live refs, command bodies, and recursive loop scopes.
- Included command prompts support declared inputs while direct caller references fail with actionable migration guidance.
- Review findings were addressed with empty-body rejection, persisted loop prompt snapshots, cold-resume-safe private compilation metadata, and three-level nested-include coverage.
- Final specialist re-review found no remaining high-confidence issues; the full workflows package suite and workflows type-check pass.

### Documentation Issues
- None. Include command compilation, lexical boundaries, script opacity, and paused-loop resume behavior are documented.

### Verdict
READY TO MERGE

### Recommended Actions
1. Let the refreshed GitHub Actions checks complete.
2. Keep #1764's future parent-run composition on the same lexical-boundary contract and add parity tests there.
3. Consider the advisory traversal simplifications in a separate refactor only if future surfaces make the duplication costly.

**Comment by Wirasm** [comment]
Addressed the remaining automated review suggestions in 8a3c42bf: documented the `when:`/`||` composition restriction and replaced the new broad `as unknown as DagNode` fixtures with `satisfies` checks. The return-type nit was already satisfied (`compile(...): CompiledLoopCommand`) and required no change.

**Comment by Wirasm** [comment]
## PR Review Summary

### Critical Issues (0 found)
| Agent | Issue | Location |
|-------|-------|----------|
| — | — | — |

### Important Issues (2 found)
| Agent | Issue | Location |
|-------|-------|----------|
| silent-failure-hunter | Included-command discovery catches every project/configured-scope error and continues to lower-precedence scopes. Because this PR turns the scan result into the executable prompt snapshot, an unreadable or concurrently deleted repo command can silently execute a home or bundled command with the same name. Continue only when a scope has no match; after a match, surface read failures with command and path context as a per-workflow load/compilation error. Direct runtime command loading already fails explicitly in this situation. | `packages/workflows/src/workflow-discovery.ts:457` |
| code-reviewer | The new command-body ownership scan mistakes the valid include macro `$INPUTS.output` for the canonical node reference `$<node>.output` before input expansion runs. A block declaring an input named `output` is therefore dropped even when the caller supplies it. Exclude syntactically valid `$INPUTS.<name>` macros from the ownership scan while preserving rewrite-before-input ordering, and add a regression test. | `packages/workflows/src/include-expander.ts:544` |

### Suggestions (7 found)
| Agent | Suggestion | Location |
|-------|------------|----------|
| silent-failure-hunter | If compiled-loop metadata is present but has neither a string `prompt` nor `error`, fail explicitly instead of silently falling back to live command lookup. Reserve fallback for truly absent metadata on ordinary loop commands. | `packages/workflows/src/dag-executor.ts:4204` |
| pr-test-analyzer | Exercise included-loop cold resume through real filesystem discovery: discover, pause, delete the command, rediscover, resume from the persisted snapshot, and separately prove a fresh run fails before provider invocation. The current composed-loop case simulates deletion by passing a `null` map entry directly to the expander. | `packages/workflows/src/dag-executor.test.ts:8472` |
| pr-test-analyzer | Combine three-level composition with a command-backed loop nested inside one or more `loop_group` bodies. Existing tests cover three include levels and recursive loop placement separately, so deleting recursive symbol preservation could leave both green. | `packages/workflows/src/include-expander.test.ts:564` |
| pr-test-analyzer | Add the distinct whitespace-only `loop.command` case: the workflow remains discoverable with a private compilation error, a fresh execution emits one actionable failure, and no provider call occurs. | `packages/workflows/src/include-expander.test.ts:884` |
| comment-analyzer | Refresh stale comments that still claim validation cannot see bash/script/approval/cancel fields, that validation covers only `when:`/`prompt:`, and that includes add zero runtime machinery; included loop commands now carry private runtime-consumed metadata. Also fix “so an every canonical ref.” | `packages/workflows/src/dag-executor.ts:784` |
| type-design-analyzer | Consider central read/write/clone helpers for `COMPILED_LOOP_COMMAND` to contain repeated intersection casts and document first-write-wins and `structuredClone` preservation. The current union is useful and sufficiently typed, so this is advisory. | `packages/workflows/src/compiled-command.ts:1` |
| code-simplifier | Normalize the optional command-content map once and keep the node-ref and input-macro walkers separate; their different grammars and surface sets make a generic shared walker less clear. | `packages/workflows/src/include-expander.ts:600` |

### Strengths
- Hermetic validation now covers canonical references, shorthand `when:`, rejection prompts, Markdown-live references, resolved command bodies, recursive loop scopes, and parent-id collision cases.
- Compiled command prompts preserve caller-input ordering, local namespacing, cold-resume snapshots, and three-level top-level composition; named scripts remain opaque.
- Focused suites passed independently: include-expander 69/69, loader 249/249, discovery command scan 2/2, and DAG executor 451/451 (771 total).
- The full `@archon/workflows` package suite, workflows type-check, changed production-file lint, formatting, bundled-default generation check, and `git diff --check` all passed.
- `bun run validate` was run and exited 2 at `check:pi-vendor-map`. The identical command at clean `origin/dev` (`2379a2c9`) failed at the same gate, and this PR changes no dependency, lockfile, generator, or Pi vendor-map file; this is base/environment-only drift rather than a PR regression.
- GitHub CI is green on Ubuntu, Windows, Docker, docs, and CodeRabbit.
- A synthetic merge with the current PR #2533 head completed without textual conflicts. The PRs overlap `authoring-workflows.md`, `dag-executor.test.ts`, and `bundled-defaults.generated.ts`; regenerate bundled defaults after integration so neither generated snapshot is lost.

### Documentation Issues
- `packages/docs-web/src/content/docs/guides/loop-nodes.md:130` says every `loop.command` file is read when the loop starts. Included loop commands are now resolved and compiled during discovery, fail before a fresh AI turn when unresolved/empty, and resume from the persisted prompt snapshot. Document the ordinary-loop versus included-loop distinction.
- `packages/docs-web/src/content/docs/guides/authoring-commands.md:29` says shared commands are loaded at runtime. Qualify this as the ordinary model and note that command bodies inside an `include:` are resolved and snapshotted during load-time composition.
- The changed authoring guide accurately covers hermetic scope, command compilation, snapshots, Markdown-live references, script opacity, and the include/entry `when:` plus `||` limitation.

### Verdict
NEEDS FIXES

### Recommended Actions
1. Make matched command-file read failures fail closed instead of falling through to a lower-precedence prompt, then add an unreadable/raced-file regression.
2. Permit the valid `$INPUTS.output` macro in included command bodies and add ordinary-command plus loop-command regression coverage.
3. Update the stale loop-node documentation and code comments.
4. Re-run the focused suites, full workflows package, type-check/lint/format/bundle checks, and `bun run validate`; record the known base-only Pi gate separately if it remains.
5. Re-run the full multi-agent review before merge. Do not merge the current head.

**Comment by Wirasm** [comment]
## PR Review Summary

### Critical Issues (0 found)
| Agent | Issue | Location |
|-------|-------|----------|
| — | — | — |

### Important Issues (0 remaining; 4 fixed)
| Agent | Resolved issue | Resolution |
|-------|----------------|------------|
| code-reviewer | `$INPUTS.output` was misclassified as a node reference in command compilation and loader validation. | Reserved macro precedence is explicit in both passes; pure-expander and real discovery coverage now exercise ordinary and loop commands. |
| code-reviewer | A matched unreadable command file could fall through to a lower-precedence command. | Matched-file read failures carry command/path/include/node context and fail closed. |
| code-reviewer | An uninspectable higher-precedence command directory could also fall through. | Only absent scopes/no match continue; non-ENOENT inspection failures become path-bearing compilation errors. |
| silent-failure-hunter | Present malformed compiled-loop metadata could fall back to live lookup. | Present metadata must contain exactly one string `prompt` or `error`; malformed/ambiguous values fail before provider invocation. |

### Suggestions (3 deferred)
| Agent | Suggestion | Rationale |
|-------|------------|-----------|
| code-simplifier | Share output-ref and input-macro traversal. | The walkers intentionally cover different surfaces; extraction would broaden this correctness fix. |
| type-design-analyzer | Add central compiled-command metadata accessors. | Current discriminated union and localized casts remain understandable; no current third use requires abstraction. |
| code-simplifier | Normalize the optional command map once. | Negligible benefit and unrelated to correctness. |

### Strengths
- Hermetic validation covers canonical refs, `when:` shorthand, approval rejection prompts, Markdown-live refs, resolved command bodies, recursive loop scopes, and parent-id collision cases.
- Included commands preserve command-first authoring while resolving bodies at load time, binding declared inputs, and rejecting implicit caller references.
- Command lookup now preserves precedence safely: matched-file and scope-inspection failures never select a lower-precedence prompt.
- Included command-backed loops retain identity plus private compiled prompt/error metadata; interactive resume prioritizes the persisted prompt snapshot after cold rediscovery or source deletion.
- Regression coverage includes `$INPUTS.output`, unreadable files/directories, malformed metadata, whitespace-only loops, three-level nested loop-group composition, and real filesystem delete/rediscover/resume.
- Code, tests, errors, docs, and comments specialists all passed the final reviewed heads after their findings were addressed.

### Documentation
- Ordinary runtime command loading versus included load-time compilation is documented.
- Inline and command-backed interactive loop snapshot behavior is documented.
- Named script source opacity and the distinction between include selector substitution and sub-run `INPUTS_*` environment delivery are documented.
- Stale `workflow.with` and `fan_out.as` reference text was corrected to match current behavior.

### Validation
- `include-expander.test.ts`: 72 passed.
- `workflow-discovery-command-scan.test.ts`: 4 passed.
- `loader.test.ts`: 250 passed.
- `dag-executor.test.ts`: 453 passed.
- Full `@archon/workflows` package suite: passed.
- `@archon/workflows` type-check: passed.
- Changed production-file ESLint, repository format check, bundled-default checks, and `git diff --check`: passed.
- `bun run validate`: exits 2 at `check:pi-vendor-map`; the same installed Pi SDK/vendor-map drift was reproduced on clean `origin/dev` before this PR and the PR changes no Pi/dependency files. A later uncached root lint likewise exposed two Pi SDK-derived errors in untouched provider files; changed production files pass lint.

### Verdict
READY — WAITING FOR CI / USER MERGE GATE

### Recommended Actions
1. Let the refreshed GitHub Actions checks for head `02ef3a1d` complete.
2. Do not merge automatically; preserve the requested user gate.
3. When integrating with #2533, rebase/revalidate the later PR because the branches overlap workflow docs/tests/generated defaults.
