### ISSUE TITLE
fix(workflows): SQLite run adoption crashes before continuation starts

### ISSUE THREAD

**Issue by Wirasm** [coleam00/Archon#2845]
## Problem

A terminal workflow run cannot be adopted on the default SQLite database. `workflow run <name> --adopt <run-id>` crashes before creating the continuation run:

```text
Error: createdBefore.toISOString is not a function
```

This breaks the engine continuation invariant delivered by #2747: after a terminal failure, an operator must be able to start the same or another workflow on the existing branch/worktree and artifacts with recorded provenance.

## Real reproduction

On 27 August 2026, run `6608041e-4d0e-4315-a86a-46e36dd789d6` was terminal `failed`, its worktree and branch were still live, and it had no adopting run.

```bash
archon workflow run archon-implement \
  --adopt 6608041e-4d0e-4315-a86a-46e36dd789d6 \
  --config .archon/config.glm-flash.yaml \
  --detach \
  "Correct PR #2833 only"
```

The detached child reached adoption resolution, emitted the error above, and exited. No new workflow run row was created and the original worktree remained unchanged.

## Expected behavior

The engine resolves the terminal estate, reuses its live worktree or materializes its surviving branch, records `adopted_from_run_id`, exposes the prior artifact directory, and starts the requested workflow.

## Actual behavior

Adoption crashes while resolving isolation history, before worktree selection or run creation.

## Proven root cause

1. SQLite stores `remote_agent_workflow_runs.started_at` as TEXT and returns it as a JavaScript string.
2. `getWorkflowRun()` types the raw row as `WorkflowRun`, but `normalizeWorkflowRun()` only parses metadata. It does not hydrate timestamps, despite `WorkflowRun.started_at` being declared as `Date`.
3. `resolveWorkflowAdoption()` passes that runtime string to `findLatestByCodebaseAndWorkingPath()`.
4. The isolation lookup accepts only `Date` and calls `.toISOString()`, producing the observed exception.

A direct read-only reproduction against the real SQLite row proved the cutoff value was `2026-08-27 07:01:38`, `typeof string`, and not a `Date`. The failure occurs before provider selection, model configuration, worktree recovery, or detached execution can affect the result.

Relevant boundaries:

- `packages/core/src/db/workflows.ts` — workflow-run row normalization
- `packages/core/src/operations/workflow-adoption.ts` — terminal estate resolution
- `packages/core/src/db/isolation-environments.ts` — dialect-specific historical cutoff query
- `packages/cli/src/commands/workflow.ts` — adoption is resolved before run creation

## Fix boundary

The database/estate boundary must accept and normalize the timestamp representation SQLite actually returns while preserving the ownership rule `environment.created_at <= run.started_at`. Do not paper over this in the CLI or provider path.

The wider false runtime promise that every persisted `WorkflowRun` timestamp is already a `Date` should remain visible rather than being duplicated as one-off coercions across new consumers.

## Regression proof

Add a real-SQLite composition test that:

1. inserts a workflow run with the SQLite TEXT timestamp representation;
2. reads it through `getWorkflowRun()`;
3. passes that actual returned `started_at` into the isolation-history lookup;
4. seeds estate rows before and after the run cutoff;
5. proves adoption selects the newest pre-cutoff estate and excludes the later row.

This composition throws before the correction. Existing adoption unit tests fabricate `Date` values, and the current SQLite isolation test also supplies an explicit `Date`, so neither covers the real boundary.

## Links

- Continuation contract: #2747
- Dogfood PR whose failed run exposed this: #2833
